event_management/apps/events/urls.py
from django.urls import path

from .views import (
    EventDetailsView,
    EventLists,
    EventListView,
    EventSearch,
    RegisterEvent,
    RegisterEventView,
    UserRegisteredEventLists,
    UserRegisteredEvents,
)

app_name = "api_events"

urlpatterns = [
    path("", UserRegisteredEventLists.as_view(), name="register_event_lists"),
    path("all/", EventLists.as_view(), name="event_lists"),
    path("<int:event_id>/", RegisterEvent.as_view(), name="event_details"),
    path("event_search/", EventSearch.as_view(), name="event_search"),
    path(
        "register/<int:event_id>/",
        RegisterEvent.as_view(),
        name="register_event",
    ),
    # api
    path("events/", EventListView.as_view(), name="events"),
    path("event/<int:event_id>/", EventDetailsView.as_view(), name="details_event"),
    path(
        "event/register/<int:event_id>/",
        RegisterEventView.as_view(),
        name="event_register",
    ),
    path(
        "registered-events/",
        UserRegisteredEvents.as_view(),
        name="registered_events",
    ),
]

event_management/urls.py
from django.contrib import admin
from django.urls import include, path
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("event_management.apps.accounts.urls")),
    path(
        "events/", include("event_management.apps.events.urls", namespace="api_events")
    ),
    path("api/", include("event_management.apps.events.urls", namespace="api_events")),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "api/schema/swagger-ui/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
]

event_management/apps/events/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Event(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    date = models.DateField()
    time = models.TimeField()
    location_name = models.CharField(max_length=200)
    available_slots = models.PositiveIntegerField()

    def __str__(self):
        return self.title


class Registration(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="registrations"
    )
    event = models.ForeignKey(
        Event, on_delete=models.CASCADE, related_name="registrations"
    )
    registration_date = models.DateTimeField(auto_now_add=True)

event_management/apps/events/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import timezone
from django.views import View
from django.views.generic import TemplateView
from rest_framework import status
from rest_framework.parsers import FormParser, MultiPartParser
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from .models import Event, Registration
from .serializers import EventSerializer


class UserRegisteredEventLists(LoginRequiredMixin, TemplateView):
    template_name = "events/register_event_lists.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        registered_events = Event.objects.filter(registrations__user=user).distinct()
        context["registered_events"] = registered_events
        return context


class EventLists(TemplateView):
    template_name = "events/event_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        events = Event.objects.all()

        event_data = []
        for event in events:
            registration = Registration.objects.filter(user=user, event=event).exists()
            event_data.append({"event": event, "is_registered": registration})

        context["events"] = event_data

        return context


class RegisterEvent(View):
    template_name = "events/event_details.html"

    def get(self, request, event_id):
        event = get_object_or_404(Event, pk=event_id)
        user = request.user
        registration = Registration.objects.filter(user=user, event=event).exists()
        context = {"event": event, "is_registered": registration}
        return render(request, self.template_name, context)

    def post(self, request, event_id):
        if not request.user.is_authenticated:
            return redirect("login")

        event = get_object_or_404(Event, pk=event_id)
        registration = Registration.objects.filter(user=request.user, event=event)

        if registration.exists():
            event.available_slots += 1
            event.save()
            registration.delete()
            return redirect("api_events:event_lists")

        else:
            if event.available_slots > 0:
                registration = Registration(
                    user=request.user, event=event, registration_date=timezone.now()
                )
                event.available_slots -= 1
                registration.save()
                event.save()

        return redirect("api_events:event_lists")


class EventSearch(View):
    template_name = "events/event_search.html"

    def get(self, request):
        query = request.GET.get("search", "")
        events = Event.objects.filter(
            Q(title__icontains=query)
            | Q(description__icontains=query)
            | Q(location_name__icontains=query)
        )
        context = {"events": events, "query": query}
        return render(request, self.template_name, context)


# APIVIEW
class EventListView(APIView):
    def get(self, request, format=None):
        events = Event.objects.all()
        serializer = EventSerializer(events, many=True)
        return Response(serializer.data)


class EventDetailsView(APIView):
    def get(self, request, event_id):
        try:
            event = Event.objects.get(pk=event_id)
            event_serializer = EventSerializer(instance=event)
            return Response(data=event_serializer.data, status=status.HTTP_200_OK)

        except Event.DoesNotExist:
            return Response(
                data={"message": "Event does not exist"},
                status=status.HTTP_404_NOT_FOUND,
            )


class RegisterEventView(APIView):
    permission_classes = [IsAuthenticated]

    def post(self, request, event_id, format=None):
        event = Event.objects.get(pk=event_id)
        registration = Registration.objects.filter(user=request.user, event=event)

        if registration.exists():
            event.available_slots += 1
            event.save()
            registration.delete()
            return Response({"event": "Registration canceled successfully."})

        else:
            if event.available_slots > 0:
                registration = Registration(
                    user=request.user, event=event, registration_date=timezone.now()
                )
                event.available_slots -= 1
                registration.save()
                return Response({"event": "Registration successful."})

            else:
                return Response(
                    {"event": "No available slots for registration."},
                    status=status.HTTP_400_BAD_REQUEST,
                )


class UserRegisteredEvents(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request, *args, **kwargs):
        user = self.request.user
        registered_events = Event.objects.filter(registrations__user=user)
        serializer = EventSerializer(registered_events, many=True)
        return Response(data=serializer.data, status=status.HTTP_200_OK)

event_management/apps/events/templates/events/event_details.html
{% extends "base.html" %} 
{% block content %} 
<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="mx-auto flex flex-wrap">
        <div class="lg:w-3/5 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          
            <div class="flex items-center justify-between mb-5">
                <h2
                  class="sm:text-3xl text-xl title-font font-medium text-gray-900 mb-4 text-transform: uppercase"
                >
                  {{event.title}}
                </h2>
                {% if user.is_authenticated and event.available_slots > 0 %}
                    <div class="flex items-center justify-between">
                        <form class="form" action="{% url 'api_events:register_event' event.pk %}" method="POST">
                            {% csrf_token %}
                            <button
                                type="submit"
                                class="{% if is_registered %}text-green-700 font-medium rounded-md text-md px-1 py-1 text-center me-2 mb-2 cursor-not-allowed{% else %} text-red-700 hover:text-white border border-red-200 hover:bg-red-800 focus:outline-none focus:ring-red-300 font-small rounded-sm text-md px-1 text-center me-2 mb-2 dark:border-red-500 dark:text-red-500 dark:hover:text-white dark:hover:bg-red-200 dark:focus:ring-red-900{% endif %}"
                                {% if is_registered %}disabled{% endif %}
                            >
                                {% if is_registered %} REGISTERED {% else %}
                                REGISTER {% endif %}
                            </button>
                        </form>
                        
                        <form class="form" action="{% url 'api_events:register_event' event.pk %}" method="POST">
                            {% csrf_token %}
                            <button
                                type="submit"
                                class="{% if is_registered %}text-red-700 hover:text-white border border-red-200 hover:bg-red-800 focus:outline-none font-small rounded-sm text-md px-1 text-center me-2 mb-2 dark:border-red-500 dark:text-red-500 dark:hover:text-white dark:hover:bg-red-200 {% else %}text-gray-700 font-medium rounded-md text-md px-1 py-1 text-center me-2 mb-2 cursor-not-allowed{% endif %}"
                                {% if is_registered %}{%else%}disabled {% endif %}
                            >
                                REMOVE
                            </button>
                        </form>
                    </div>
                {%else%}
                <button
                class="text-red-700 hover:text-white border border-red-200 hover:bg-red-800 focus:outline-none focus:ring-red-300 font-small rounded-sm text-sm px-1 text-center me-2 mb-2 dark:border-red-500 dark:text-red-500 dark:hover:text-white dark:hover:bg-red-200 dark:focus:ring-red-900"
            >
             No available slots   
            </button>
                {% endif %}
              </div>

          <p class="leading-relaxed mb-4">
              {{event.description}}
          </p>
        </div>

        <div class="lg:w-2/5 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
            <div class="flex border-t border-gray-200 py-2">
                <span class="text-gray-500">Location</span>
                <span class="ml-auto text-gray-900">{{event.location_name}}</span>
              </div>
              <div class="flex border-t border-gray-200 py-2">
                <span class="text-gray-500">Time</span>
                <span class="ml-auto text-gray-900">{{event.time}}</span>
              </div>
              <div class="flex border-t border-gray-200 py-2">
                <span class="text-gray-500">Available Slots</span>
                <span class="ml-auto text-gray-900">{{event.available_slots}}</span>
              </div>
              <div class="flex border-t border-b mb-6 border-gray-200 py-2">
                <span class="text-gray-500">Date</span>
                <span class="ml-auto text-gray-900">{{event.date}}</span>
              </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

event_management/apps/events/templates/events/event_list.html
{% extends "base.html" %} {% block content %}

<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="flex items-center flex-wrap pb-4 mb-4 border-b-2 border-gray-100 mt-auto w-full justify-between">
      <div></div>
     <form class="lg:w-2/5 w-full" action="{% url 'api_events:event_search' %}" method="GET">   
       <label for="default-search" class="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-white">Search</label>
       <div class="relative">
           <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
               <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                   <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
               </svg>
           </div>
           <input type="search" name="search" id="default-search" class="block w-full p-4 ps-10 text-sm text-gray-900  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white" placeholder="Search Events..." required>
           <button type="submit" class="text-white absolute end-2.5 bottom-2.5 bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Search</button>
       </div>
     </form>
    </div>
    <div class="flex flex-wrap">
      {% for event_data in events %}
      <div class="p-1 md:w-1/3 flex flex-col items-start">
        <div class="pl-5 pr-5 border border-gray-600">
          <div class="flex items-center justify-between">
            <h2
              class="sm:text-3xl text-xl title-font font-medium text-gray-900 mt-4 mb-4"
            >
              {{event_data.event.title}}
            </h2>
            {% if user.is_authenticated and event_data.event.available_slots > 0 %}
                <div class="flex items-center justify-between">
                    <form class="form" action="{% url 'api_events:register_event' event_data.event.pk %}" method="POST">
                        {% csrf_token %}
                        <button
                            type="submit"
                            class="{% if event_data.is_registered %}text-green-700 font-medium rounded-md text-xs px-1 py-1 text-center me-2 mb-2 cursor-not-allowed{% else %} text-red-700 hover:text-white border border-red-200 hover:bg-red-800 focus:outline-none focus:ring-red-300 font-small rounded-sm text-sm px-1 text-center me-2 mb-2 dark:border-red-500 dark:text-red-500 dark:hover:text-white dark:hover:bg-red-200 dark:focus:ring-red-900{% endif %}"
                            {% if event_data.is_registered %}disabled{% endif %}
                        >
                            {% if event_data.is_registered %} REGISTERED {% else %}
                            REGISTER {% endif %}
                        </button>
                    </form>
                    
                    <form class="form" action="{% url 'api_events:register_event' event_data.event.pk %}" method="POST">
                        {% csrf_token %}
                        <button
                            type="submit"
                            class="{% if event_data.is_registered %}text-red-700 hover:text-white border border-red-200 hover:bg-red-800 focus:outline-none font-small rounded-sm text-sm px-1 text-center me-2 mb-2 dark:border-red-500 dark:text-red-500 dark:hover:text-white dark:hover:bg-red-200 {% else %}text-gray-700 font-medium rounded-md text-xs px-1 py-1 text-center me-2 mb-2 cursor-not-allowed{% endif %}"
                            {% if event_data.is_registered %}{%else%}disabled {% endif %}
                        >
                            REMOVE
                        </button>
                    </form>
                </div>
            {%else%}
            <button
            class="text-red-700 hover:text-white border border-red-200 hover:bg-red-800 focus:outline-none focus:ring-red-300 font-small rounded-sm text-sm px-1 text-center me-2 mb-2 dark:border-red-500 dark:text-red-500 dark:hover:text-white dark:hover:bg-red-200 dark:focus:ring-red-900"
        >
         No available slots   
        </button>
            {% endif %}
          </div>
          <p class="leading-relaxed mb-8">
            {{event_data.event.description |truncatewords:20}}
          </p>
          <div
            class="flex items-center flex-wrap pb-4 mb-4 border-b-2 border-gray-100 mt-auto w-full justify-between"
          >
          <form class="form" action="" method="GET">
            {% csrf_token %}
            <a href="{% url 'api_events:event_details' event_data.event.pk %}" class="text-indigo-500 inline-flex items-center">
              More
              <svg
                class="w-4 h-4 ml-2"
                viewBox="0 0 24 24"
                stroke="currentColor"
                stroke-width="2"
                fill="none"
                stroke-linecap="round"
                stroke-linejoin="round"
              >
                <path d="M5 12h14"></path>
                <path d="M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </form>
            <div>
                <span
              class="text-gray-400 text-sm border-r-2 border-gray-200 mr-1 ml-1"
            >
              
              {{event_data.event.date}}
            </span>

            <span
              class="text-gray-400 text-sm border-r-2 border-gray-200 mr-1 ml-1"
            >
              {{event_data.event.time}}
            </span>
            <span
              class="text-gray-400 text-sm border-r-2 border-gray-200 mr-1 ml-1"
            >
              {{event_data.event.location_name}}
            </span>
            <span
              class="text-gray-400 text-sm  mr-1 ml-1"
            >
              slots: {{event_data.event.available_slots}}
            </span>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
{% endblock content %}

event_management/apps/events/templates/events/event_search.html
<!-- event_search.html -->
{% extends 'base.html' %} {% block content %}
<h1>Event Search Results</h1>
<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="flex flex-wrap">
      {% if events %} {% for event in events %}
      <div class="p-1 md:w-1/3 flex flex-col items-start">
        <div class="pl-5 pr-5 border border-gray-600">
          <div class="flex items-center justify-between">
            <h2
              class="sm:text-3xl text-xl title-font font-medium text-gray-900 mt-4 mb-4"
            >
              {{event.title}}
            </h2>
            {% if user.is_authenticated%}
            <div class="flex items-center justify-between">
              <span
                class="text-green-700 font-medium rounded-md text-xs px-1 py-1 text-center me-2 mb-2 cursor-not-allowed"
              >
                REGISTERED
              </span>

              <form
                class="form"
                action="{% url 'api_events:register_event' event.pk %}"
                method="POST"
              >
                {% csrf_token %}
                <button
                  type="submit"
                  class="text-red-700 hover:text-white border border-red-200 hover:bg-red-800 focus:outline-none font-small rounded-sm text-sm px-1 text-center me-2 mb-2 dark:border-red-500 dark:text-red-500 dark:hover:text-white dark:hover:bg-red-200"
                >
                  REMOVE
                </button>
              </form>
            </div>
            {% endif %}
          </div>
          <p class="leading-relaxed mb-8">
            {{event.description |truncatewords:20}}
          </p>
          <div
            class="flex items-center flex-wrap pb-4 mb-4 border-b-2 border-gray-100 mt-auto w-full justify-between"
          >
            <form class="form" action="" method="GET">
              {% csrf_token %}
              <a
                href="{% url 'api_events:event_details' event.pk %}"
                class="text-indigo-500 inline-flex items-center"
              >
                More
                <svg
                  class="w-4 h-4 ml-2"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                  stroke-width="2"
                  fill="none"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                >
                  <path d="M5 12h14"></path>
                  <path d="M12 5l7 7-7 7"></path>
                </svg>
              </a>
            </form>
          </div>
        </div>
      </div>
      {% endfor %} {% else %}
      <p>No events found</p>
      {% endif %}
    </div>
  </div>
</section>
{% endblock %}

event_management/apps/events/templates/events/register_event_lists.html
{% extends "base.html" %} {% block content %}

<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="flex flex-wrap">
      {% if registered_events %} {% for event in registered_events %}
      <div class="p-1 md:w-1/3 flex flex-col items-start">
        <div class="pl-5 pr-5 border border-gray-600">
          <div class="flex items-center justify-between">
            <h2
              class="sm:text-3xl text-xl title-font font-medium text-gray-900 mt-4 mb-4"
            >
              {{event.title}}
            </h2>
            {% if user.is_authenticated%}
            <div class="flex items-center justify-between">
              <span
                class="text-green-700 font-medium rounded-md text-xs px-1 py-1 text-center me-2 mb-2 cursor-not-allowed"
              >
                REGISTERED
              </span>

              <form
                class="form"
                action="{% url 'api_events:register_event' event.pk %}"
                method="POST"
              >
                {% csrf_token %}
                <button
                  type="submit"
                  class="text-red-700 hover:text-white border border-red-200 hover:bg-red-800 focus:outline-none font-small rounded-sm text-sm px-1 text-center me-2 mb-2 dark:border-red-500 dark:text-red-500 dark:hover:text-white dark:hover:bg-red-200"
                >
                  REMOVE
                </button>
              </form>
            </div>
            {% endif %}
          </div>
          <p class="leading-relaxed mb-8">
            {{event.description |truncatewords:20}}
          </p>
          <div
            class="flex items-center flex-wrap pb-4 mb-4 border-b-2 border-gray-100 mt-auto w-full justify-between"
          >
            <form class="form" action="" method="GET">
              {% csrf_token %}
              <a
                href="{% url 'api_events:event_details' event.pk %}"
                class="text-indigo-500 inline-flex items-center"
              >
                More
                <svg
                  class="w-4 h-4 ml-2"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                  stroke-width="2"
                  fill="none"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                >
                  <path d="M5 12h14"></path>
                  <path d="M12 5l7 7-7 7"></path>
                </svg>
              </a>
            </form>

            <div>
              <span
                class="text-gray-400 text-sm border-r-2 border-gray-200 mr-1 ml-1"
              >
                {{event.date}}
              </span>

              <span
                class="text-gray-400 text-sm border-r-2 border-gray-200 mr-1 ml-1"
              >
                {{event.time}}
              </span>
              <span
                class="text-gray-400 text-sm border-r-2 border-gray-200 mr-1 ml-1"
              >
                {{event.location_name}}
              </span>
              <span class="text-gray-400 text-sm mr-1 ml-1">
                slots: {{event.available_slots}}
              </span>
            </div>
          </div>
        </div>
      </div>
      {% endfor %} {% else %}
      <p>You haven't registered for any events yet.</p>
      {% endif %}
    </div>
  </div>
</section>
{% endblock content %}